insert into article values (
	'how_idea_geekswimmers_emerged',
    'How The Idea Behind GeekSwimmers Emerged', 
    'In the afternoon of that cold December 1st, I was volunteering at the ROW Novice Meet as an electronic operator, the person ensuring the timing system is in sync with the actual meet. My 9-year-old daughter was competing for the second time in that season. Far from there was my 11-year-old son, who was competing at the Border City Meet, in Windsor. I had just arrived at my position on deck, familiarizing myself with the time management system, when Mike, another proud parent volunteering at the same meet, approached me to say...', 
   	false, 
   	'2024-01-15', 
   	'articles/how-idea-geekswimmers-emerged.md', 
   	'how-idea-geekswimmers-emerged.jpg', 
   	'By Jmex60 - Own work, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=4611001', 
   	'The events that led to the creation of GeekSwimmers.');

insert into article values (
	'how_time_benchmark_works', 
    'How Time Benchmark Works', 
    'Those who build GeekSwimmers believe that comparing yourself to others can undermine your confidence and halt your progress. Each swimmer is on a unique journey, shaped by a lot of factors. A focus on personal progress, rather than others'' achievements, is the most productive approach to improving your swimming skills. That''s why we use time standards, not other swimmers, to compare your times with.', 
   	true, 
   	'2024-02-25', 
   	'articles/how-time-benchmark-works.md', 
   	'how-time-benchmark-works.png', 
   	'Generated by OpenAI DALL-E', 
   	'It turned out to be harder than we expected, so we made it simple.');