[database]
url = "postgres://geekswimmers_usr:secretpassword@localhost:5432/geekswimmers"
maxopenconns = 10
connmaxlifetime = 30 # minutes

[server]
port = 8080
sessionkey = ""

[recaptcha]
sitekey = ""
secretkey = ""

[monitoring]
googleanalytics = ""

[miscellaneous]
feedbackform = ""