[database]
url = "postgres://geekswimmers_usr:secretpassword@localhost:5432/geekswimmers"
maxopenconns = 10
connmaxlifetime = 30 # minutes

[server]
port = 8080
sessionkey = ""

[email]
server = ""
port = 521
transport = "TLS"
username = ""
password = ""
from = ""

[recaptcha]
sitekey = ""
secretkey = ""

[monitoring]
googleanalytics = ""

[miscellaneous]
feedbackform = ""