version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run main.go
  db:
    image: postgres:alpine
    hostname: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5431:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: